CREATE TABLE public.company_holidays (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date date NOT NULL,
  end_date date NOT NULL,
  note text,
  created_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX holidays_date_range ON public.company_holidays (start_date, end_date);

-- Collapse N per-employee holiday leave rows into one company holiday per range
INSERT INTO public.company_holidays (start_date, end_date, note, created_by, created_at)
SELECT
  start_date,
  end_date,
  MAX(note) AS note,
  MIN(created_by) AS created_by,
  now() AS created_at
FROM public.employee_leaves
WHERE leave_type = 'holiday'
GROUP BY start_date, end_date;

DELETE FROM public.employee_leaves
WHERE leave_type = 'holiday';
