CREATE TABLE public.employee_leaves (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id integer NOT NULL REFERENCES public.employees (employee_id) ON DELETE CASCADE,
  start_date date NOT NULL,
  end_date date NOT NULL,
  leave_type varchar(32) NOT NULL DEFAULT 'vacation',
  note text,
  status varchar(32) NOT NULL DEFAULT 'approved',
  created_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX leaves_emp_range ON public.employee_leaves (employee_id, start_date, end_date);
