CREATE TABLE public.hik_biometric_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id integer NOT NULL,
  employee_name text,
  log_date date,
  log_time time,
  log_date_time timestamp
);

CREATE INDEX logs_date ON public.hik_biometric_logs (log_date);
CREATE INDEX logs_employee_date ON public.hik_biometric_logs (employee_id, log_date);
